### ISSUE TITLE
Rename `get_time_step` of controllers

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#161]
While working on the docu, I've come across the subtle difference between `get_time_step` and `get_time`. The first returns the width of one time step (`\Delta t`) while the latter returns `t_0` of the current time step.

I suggest to rename `get_time_step` to `get_step_width` or `get_delta_step`.

**Comment by memmett** [comment]
I use language like "what time step are you using?" fairly regularly so the current naming conventions seems natural to me (oh ya, and I wrote it!).  I'd go for `get_step_width` or `get_step_size`, but `get_delta_step` seems awkward.

**Comment by torbjoernk** [comment]
`get_step_size` seems a good choice. @pancetta, @danielru, any comments?

**Comment by memmett** [comment]
Should we add aliases `get_t` for `get_time` and `get_dt` for `get_step_size` too?
