### ISSUE TITLE
consider requiering CMake v3.x for handy features

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#164]
The new(er) versions of CMake (>=3.0) provide a couple really nice and handy functions and macros to easy specification of compiler requirements etc.

We should consider requiring CMake 3.x to clean up our CMake files. 3.0 should be _old enough_ to be broadly available.

**Comment by memmett** [comment]
Requiring 3.1 is fine with me.

**Comment by torbjoernk** [comment]
I'm bumping this to 1.0.0 again as CMake 3.1 is the one we would go for and this is jet not available on our supercomputers.

**Comment by memmett** [comment]
Closing this since dependency picture is changing...
