### ISSUE TITLE
"fix" logging output on MPI-parallelized runs

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#166]
When running in parallel with MPI, the logging output should somehow be differently handled than in a serial environment. There come two options to my mind:

1. make all calls to easylogging++ a no-op (via preprocessor guards)
2. use MPI-IO and configure easylogging++ to only write to those MPI-IO files.

Option one is a low-hanging fruit and is easy to realize. The second option is probably the one to go for in the long run but requires some more work to get accomplished.

Comments?

**Comment by memmett** [comment]
You could also have each MPI rank write to their own logging file... just need a tiny bit of extra logic to create unique logging file names for each rank.  Might be a reasonable solution in the short term instead of having to get down and dirty with MPI-IO.

**Comment by pancetta** [comment]
+1. No need to worry about this for now. Data output coming from
PFASST++ is supposed to be low anyway, the spatial solver/application
will take care of big volume data.

Have a logging file in plain text for each rank in time (and only one in
space for that matter, e.g. each root per spatial communicator) should
give you no more than 100ish files per run, each containing only some
status messages.

**Comment by dasmy** [comment]
ey, Du hast Urlaub :-P

Am 07/04/15 um 20:09 schrieb Robert Speck:
> +1. No need to worry about this for now. Data output coming from
> PFASST++ is supposed to be low anyway, the spatial solver/application
> will take care of big volume data.
>
> Have a logging file in plain text for each rank in time (and only one in
> space for that matter, e.g. each root per spatial communicator) should
> give you no more than 100ish files per run, each containing only some
> status messages.
>
> On 07.04.15 18:49, Matthew Emmett wrote:
> > You could also have each MPI rank write to their own logging file...
> > just need a tiny bit of extra logic to create unique logging file names
> > for each rank. Might be a reasonable solution in the short term instead
> > of having to get down and dirty with MPI-IO.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/Parallel-in-Time/PFASST/issues/166#issuecomment-90642731>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Parallel-in-Time/PFASST/issues/166#issuecomment-90682918>.
>


-- 
Dr. Mathias Winkel
Centre for Computational Medicine in Cardiology (CCMC)

University of Lugano
Institute of Computational Science
Via Giuseppe Buffi 13
CH-6900 Lugano

Tel: +41 (0)58 666 4973
Email: mathias.winkel@usi.ch
Web: http://icsweb.inf.unisi.ch/cms/index.php/people/141-mathias-winkel.html

**Comment by torbjoernk** [comment]
So I just did the first test run on JUQUEEN. Works really nice. Had to do a few tweaks here and there (going to make a PR for that). Now we just need a real-world example with space-only-communicators. :wink:
