### ISSUE TITLE
Remove "autobuild" and friends?

### ISSUE THREAD

**Issue by memmett** [Parallel-in-Time/PFASST#190]
In the interest of having fewer lines of code in the "core", should we remove the "autobuild" stuff?

Is anyone using this (aside from the Advection/Diffusion example)?

**Comment by torbjoernk** [comment]
I've to think a little further about this. Though I've never actually used this autobuild stuff, it seems neat and handy. Though probably targeted towards more advanced users able to wrap their heads around this. At first glance the API seems not transparent. Maybe just a lack of documentation. But I'm still undecided.
