### ISSUE TITLE
add documentation for `pfasst::VERSION` and `PFASST_DEFAULT_RANDOM_SEED`

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#191]
Both entities are getting defined and generated by CMake during configure (`PFASST_DEFAULT_RANDOM_SEED`) or even later during compilation (`pfasst::VERSION`). Thus they are unknown to Doxygen in case neither CMake nor `make set_version` have been run before.

Either add in-place documentation in `cmake/site_config.hpp.in` and make Doxygen parse this file as well, or add out-of-place documentation of these two entities somewhere else (e.g. `include/pfasst.hpp`).

**Comment by memmett** [comment]
Closed by #207
