### ISSUE TITLE
PFASST does not ISend data on finest level

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#215]
I did a little further debugging (with the `mpi_pfasst` example on the `feature/fix-mpi` branch of PR #212) and it turned out, that PFASST is not triggering non-blocking sends on the finest level. Although, the matching non-blocking receive requests are executed.

On the coarse level everything seems fine.

**Comment by memmett** [comment]
@torbjoernk How are you detecting that?  Which MPI implementation are you using?  What about the middle level?

It may be the case that an `Isend` reduces to a `Send` -- depends on the implementation.

**Comment by torbjoernk** [comment]
I should have said that. MPICH 3.1.2 in a debug build. Middle level? There are only two in the `mpi_pfasst` example.

I'm detecting it by adding additional debug logging of the form
```{.cpp}
CLOG(DEBUG, "Encap") << "blocking recieve from rank " << src << " with tag=" << tag;
err = MPI_Recv(this->data(), sizeof(scalar) * this->size(), MPI_CHAR, src, tag, mpi.comm, &stat);
check_mpi_error(err);
CLOG(DEBUG, "Encap") << "recieved blocking from rank " << src << " with tag=" << tag << ": " << stat;
```
and then grepping those lines from the log files.

I'll push my changes to the PR #212.

**Comment by memmett** [comment]
@torbjoernk I've looked through my logs locally and I don't see any problems (maybe fixing the mismatched send/recv also fixed this).  Can you check again?

**Comment by torbjoernk** [comment]
Indeed, fixed.
