### ISSUE TITLE
Bugfix Release v0.5.0

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#217]
As we've been doing a bunch of bug fixes, I think it's time for thinking about a release before v1.0.0 incorporating those things. I don't want to call it a patch (i.e. v0.4.1) mainly because we've also added a few enhancements (mainly related to logging and configuration).

I'd like to get this release out before [PASC 15 in Zurich (June 1-3 2015)](http://www.pasc15.org/) where I'll talk a little bit about PFASST++.

From my point of view, the only thing to complete is merging #212 including a fix to the number of rhs evaluations.

**Comment by memmett** [comment]
Releasing 0.5.0 sounds good to me.  I looked in the number of evals and the change is expected.  On the way up the V-cycle we used to avoid calling `interpolate_initial` but now we always call it.  That's the difference, and the new behaviour is correct.
