### ISSUE TITLE
Handling of site_config requires CMake

### ISSUE THREAD

**Issue by memmett** [Parallel-in-Time/PFASST#225]
It would be nice if this dependency was removed...

**Comment by torbjoernk** [comment]
How would you process that otherwise? How would you configure the Makefiles when not having CMake?

Edit: And that is not a "bug". I see it as a "feature".

**Comment by memmett** [comment]
@torbjoernk If you don't have CMake then you have to figure out that `site_config.hpp` is missing, and then you have to figure out how to make your own and where to put it.  In that sense, it is certainly a bug -- the software doesn't even compile if you don't use CMake.

Currently `site_config.hpp` is generated once from `site_config.hpp.in` by CMake and then updated by our Python script.  The only information it contains is `pfasst::VERSION`.

I propose we:
1. Add a default `site_config.hpp` file to the repository with a value of "UNKNOWN" (or something like that) for `pfasst::VERSION`.
2. Remove `site_config.hpp.in` and tell CMake that it doesn't have to do anything with it.
3. Continue allowing our Python script to update `site_config.hpp`.

This results in: users being able to compile PFASST++ out of the box with their own build system without requiring CMake.  They can optionally add their own rule to update `pfasst::VERSION` if they wish (possibly using our Python script). From our perspective nothing really changes... our Python script still gets run when we use CMake and `pfasst::VERSION` gets set properly.

I personally don't mind using CMake but ideally we can make it as easy as possible for others to use their own build systems... removing this `site_config.hpp` hurdle would make that easier.

**Comment by pancetta** [comment]
I second that. We need to have an easy way of incorporating PFASST++
into other build systems, i.e. an easy way to compile it without CMake.
