### ISSUE TITLE
add support for Travis

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/PFASST#236]
Jenkins continues to throw up and keeps breaking due to updates of Jenkins itself and its plugins. We don't want to maintain it any more.

Once the dependency on Boost (cf. #231) we should be fine using Travis for the main tests and generation of the documentation. Though no MPI tests would be possible there.

**Comment by pancetta** [comment]
We will continue using Jenkins on a different platform, though (not
maintained by us). MPI tests should be possible there.

**Comment by torbjoernk** [comment]
Fixed by #240
